### ISSUE TITLE
double POI or HP showing as POI on map

### ISSUE THREAD

**Issue by jwahner** [shawngmc/gw2-map-web#16]
Zone: Curse Shore Location: The Wreck of the Golden Vanity

In game map shows one POI + one Hero Point. 

![image](https://user-images.githubusercontent.com/22228517/30096319-f51e069e-9294-11e7-9e13-4b3fd75710cf.png)

**Comment by shawngmc** [comment]
This was a side effect of the 'instance' maps that weren't marked. These should be fixed now; keep an eye out for missing points/zones.
